---
# Configure your freshly installed software
- hosts: all
  roles:
  - role: dotfiles
  - role: legit
  - role: dock
    apps:
      - /Applications/Google Chrome.app
      - /Applications/Skype.app
      - /Applications/IntelliJ IDEA CE.app
      - /Applications/Sublime Text.app
      - /Applications/iTerm.app
      - /Applications/LibreOffice.app
    folders:
    - path: ~/Downloads
      sort: datemodified
