---
# Configure your freshly installed software
- hosts: all
  roles:
  #- role: osx
  - role: homedir
  - role: dotfiles
  - role: jetbrains
  - role: legit
  - role: dock
    apps:
      - /Applications/Google Chrome.app
      - /Applications/Skype.app
      - /Applications/IntelliJ IDEA 13.app
      - /Applications/Sublime Text.app
      - /Applications/iTerm.app
    folders:
    - path: ~/Downloads
      sort: datemodified
