---
- hosts: all
  tasks:
  - name: Tap Hombrew
    homebrew_tap: tap={{ item }}
    with_items:
      - homebrew/binary
      - caskroom/fonts
  - name: Install fonts
    homebrew_cask: name={{ item }}
    with_items:
      - font-inconsolata-dz-for-powerline
      - font-hack
      - font-source-code-pro
  - name: Install base homebrew packages
    homebrew: name={{ item.name }} install_options={{ item.options }} state=latest
    with_items:
      - { name: 'go', options: '--cross-compile-all' }
      - { name: 'heroku-toolbelt', options: '' }
      - { name: 'imagemagick', options: '' }
      - { name: 'docker', options: '' }
      - { name: 'docker-compose', options: '' }
      - { name: 'docker-machine', options: '' }
      - { name: 'mercurial', options: '' }
      - { name: 'git', options: '' }
      - { name: 'bazaar', options: '' }
      - { name: 'direnv', options: '' }
      - { name: 'git-flow-avh', options: '' }
      - { name: 'maven', options: '' }
      - { name: 'gradle', options: '' }
      - { name: 'python', options: '' }
      - { name: 'node', options: '' }
      - { name: 'ruby', options: '' }
      - { name: 'postgres', options: '' }
      - { name: 'mysql', options: '' }
      - { name: 'zsh', options: '' }
      - { name: 'pgcli', options: '' }
      - { name: 'mycli', options: '' }
      - { name: 'vim', options: '--env-std --override-system-vi' }
      - { name: 'awscli', options: '' }
      - { name: 'nvm', options: '' }
  - name: Install heroku plugins
    command: heroku plugins:install {{ item }}
    with_items:
      - heroku-pg-extras
  - name: Install ruby gems
    gem: name={{ item }} state=latest user_install=yes
    with_items:
      - bundler
      - homesick
      - git-smart
      - lunchy
      - ghost
  - name: Set NPM prefix
    command: /usr/local/bin/npm config set prefix '~/.npm-packages'
  - name: Install NPM packages
    npm: name={{ item }} global=yes state=latest
    with_items:
      - grunt-cli
      - bower
      - yo
      - jshint
      - ember-cli
      - eslint
  - name: Create GOPATH dir
    file: state=directory path="~/Golang"
  - name: Install default Go packages
    shell: GOPATH=~/Golang go get {{ item.package }}
    with_items:
      - { package: golang.org/x/tools/cmd/gotype }
      - { package: golang.org/x/tools/cmd/goimports }
      - { package: golang.org/x/tools/cmd/cover }
      - { package: golang.org/x/tools/cmd/guru }
      - { package: golang.org/x/tools/cmd/gorename }
      - { package: github.com/nsf/gocode }
      - { package: github.com/alecthomas/gometalinter }
      - { package: github.com/golang/lint/golint }
      - { package: github.com/rogpeppe/godef }
      - { package: github.com/kisielk/errcheck }
      - { package: github.com/jstemmer/gotags }
      - { package: github.com/klauspost/asmfmt/cmd/asmfmt }
      - { package: github.com/fatih/motion }
      - { package: github.com/zmb3/gogetdoc }
      - { package: github.com/josharian/impl }
      - { package: github.com/constabulary/gb/... }
  - name: Create VIM bundle directory
    file: path=~/.vim/bundle state=directory recurse=true
  - name: Create VIM autoload directory
    file: path=~/.vim/autoload state=directory recurse=true
  - name: install pathogen
    command: curl -LSso ~/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim
  - name: install vim plugins
    git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.name }}
    with_items:
      - { repo: 'https://github.com/mileszs/ack.vim.git', name: 'ack.tool' }
      - { repo: 'https://github.com/vim-scripts/molokai.git', name: 'molokai.color' }
      - { repo: 'https://github.com/scrooloose/nerdtree.git', name: 'nerdtree.tool' }
      - { repo: 'https://github.com/jeetsukumaran/vim-buffergator.git', name: 'buffergator.tool' }
      - { repo: 'https://github.com/tpope/vim-fugitive.git', name: 'fugitive.tool' }
      - { repo: 'https://github.com/fatih/vim-go.git', name: 'go.lang' }
      - { repo: 'https://github.com/pangloss/vim-javascript.git', name: 'javascript.lang' }
      - { repo: 'https://github.com/mmalecki/vim-node.js.git', name: 'nodejs.lang' }
      - { repo: 'https://github.com/kien/ctrlp.vim.git', name: 'ctrlp.tool' }
      - { repo: 'https://github.com/scrooloose/nerdcommenter.git', name: 'nerdcommenter.tool' }
      - { repo: 'https://github.com/ervandew/supertab.git', name: 'supertab.tool' }
      - { repo: 'https://github.com/Lokaltog/vim-easymotion.git', name: 'easymotion.tool' }
      - { repo: 'https://github.com/tpope/vim-git.git', name: 'git.lang' }
      - { repo: 'https://github.com/tfnico/vim-gradle.git', name: 'gradle.lang' }
      - { repo: 'https://github.com/groenewege/vim-less.git', name: 'less.lang' }
      - { repo: 'https://github.com/bronson/vim-trailing-whitespace.git', name: 'trailing-whitespace.tool' }
      - { repo: 'https://github.com/terryma/vim-multiple-cursors.git', name: 'multiple-cursors.tool' }
      - { repo: 'https://github.com/scrooloose/syntastic.git', name: 'syntastic.tool' }
      - { repo: 'https://github.com/maksimr/vim-jsbeautify.git', name: 'jsbeautify.tool' }
      - { repo: 'https://github.com/tpope/vim-sensible.git', name: 'vim-sensible.config' }
      - { repo: 'https://github.com/majutsushi/tagbar.git', name: 'tagbar.tool' }
      - { repo: 'https://github.com/vim-scripts/ZoomWin.git', name: 'ZoomWin.tool' }
      - { repo: 'https://github.com/chriskempson/base16-vim.git', name: 'base16.color' }
      - { repo: 'https://github.com/SirVer/ultisnips.git', name: 'utilsnips.tool' }
      - { repo: 'https://github.com/AndrewRadev/splitjoin.vim.git', name: 'splitjoin.tool' }
