---
# link correct paths in home directory

- name: determine linked document location
  command: test -L ~/Documents
  ignore_errors: True
  register: doc_linked

- name: backup and move current documents
  command: sudo mv ~/Documents ~/Documents.backup
  ignore_errors: True
  when: doc_linked|failed

- name: symlink to dropbox
  file: state=link src="~/Dropbox/Documents" dest="~/Documents" force=true